<a href="https://colab.research.google.com/github/fallcat/python-tutorial/blob/main/numpy/deepcopy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deepcopy

In python, primitive types like int, str, float can be copied safely and it will be actual copies. 

But objects like list, numpy array, etc. are copied by reference. If you copy them by just making another variable equal to them and then modify them in-place, you might mess up the original variable!

In [8]:
import numpy as np
x = np.array([1, 2, 3, 4, 5, 6])

In [9]:
x

array([1, 2, 3, 4, 5, 6])

In [10]:
y = x

In [11]:
# if you do an in-place shuffle like this (note the there is no return value)
np.random.shuffle(y)

In [12]:
# y will get shuffled
y

array([1, 4, 6, 5, 2, 3])

In [13]:
# but so will x
x

array([1, 4, 6, 5, 2, 3])

In [14]:
# This is because x and y are pointing to the same thing!
# In order to avoid this, you need to use copy.deepcopy to make a real copy
import copy
x = np.array([1, 2, 3, 4, 5, 6])
y = copy.deepcopy(x)
np.random.shuffle(y)
print("y", y)
print("x", x)

y [6 1 2 4 3 5]
x [1 2 3 4 5 6]


In [15]:
# For numpy, you can also make deepcopy by simply initialize another np.array
# using the previous array
import copy
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array(x)
np.random.shuffle(y)
print("y", y)
print("x", x)

y [4 5 2 1 3 6]
x [1 2 3 4 5 6]
